alter table m_packagingstructure add active int(1) default 0;
update m_packagingstructure set active=1;
alter table m_sales_staff add active int(1) default 0;
alter table m_sales_staff_area add active int(1) default 0;
alter table m_sales_zone add active int(1) default 0;
alter table m_sample_product add active int(1) default 0;
alter table m_scheme add active int(1) default 0;
alter table m_scheme_assign add active int(1) default 0;
alter table m_scheme_product add active int(1) default 0;
alter table m_sec_edu_cess_ratelist add active int(1) default 0;
alter table m_set_monitoring_param add active int(1) default 0;
alter table m_sf_product add active int(1) default 0;
alter table m_sf_product_entry add active int(1) default 0;
alter table m_sf_product_varstaff add active int(1) default 0;
alter table m_shipping_company add active int(1) default 0;
alter table m_shipping_company_contact add active int(1) default 0;
alter table m_state add active int(1) default 0;
alter table m_state_vat add active int(1) default 0;
alter table m_state_vat_entry add active int(1) default 0;
update m_shipping_company set active=1;
alter table m_city add active int(1) default 0;
update m_city set active=1;
alter table m_loading_port add active int(5) default 0;
update m_loading_port set active=1;
alter table m_exporter add active int(1) default 0;
update m_exporter set active=1;
alter table m_doc_instructions_chk add active int(1) default 0;
update m_doc_instructions_chk set active=1;
alter table m_carriage_mode add active int(1) default 0;
update m_carriage_mode set active=1;
alter table m_operation_type add active int(1) default 0;
update m_operation_type set active=1;
alter table m_monitoring_parameters add active int(1) default 0;
update m_monitoring_parameters set active=1;
alter table m_billing_company add active int(1) default 0;
alter table m_billing_company_bank_ac add active int(1) default 0;
alter table m_common_reason add active int(1) default 0;
alter table m_common_reason_chk add active int(1) default 0;
