alter table m_currency add active int(1) default 0;
alter table m_currency_ratelist add active int(1) default 0;
alter table m_customer add active int(1) default 0;
alter table m_customer_brand add active int(1) default 0;
alter table m_customer_contact add active int(1) default 0;
alter table m_customer_payment_terms add active int(1) default 0;
alter table m_customer_shipping add active int(1) default 0;
alter table m_companydetails add active int(1) default 0;
alter table m_companydetails_bank add active int(1) default 0;
alter table m_competitor add active int(1) default 0;
alter table m_country add active int(1) default 0;
alter table m_country_port add active int(1) default 0;
alter table m_freezingstage add active int(1) default 0;
alter table m_frzn_pkg_rate add active int(1) default 0;
alter table m_frzn_pkg_rate_grade add active int(1) default 0;
alter table m_frzn_pkg_rate_list add active int(1) default 0;
alter table m_ingredient add active int(1) default 0;
alter table m_ingredient_rate add active int(1) default 0;
alter table m_ingredient_ratelist add active int(1) default 0;
alter table m_installed_capacity add active int(1) default 0;
alter table m_freezercapacity add active int(1) default 0;
update m_freezercapacity set active=1;
alter table m_status add active int(1) default 0;
update m_status set active=1;
alter table m_labellingstage add active int(1) default 0;
update m_labellingstage set active=1;
alter table m_usd add active int(1) default 0;
update m_labellingstage set active=1;
alter table m_usd add active int(1) default 0;
update m_currency set active=1;
alter table m_country add active int(1) default 0;
alter table m_country_port add active int(1) default 0;