alter table m_agent add active int(1) default 0;
update m_agent set active=1;
alter table m_processingactivities add active int(1) default 0;
update m_processingactivities set active=1;
alter table m_dam_setting add active int(1) default 0;
update m_dam_setting set active=1;
alter table m_pkg_group add active int(1) default 0;
update m_pkg_group set active=1;
alter table m_prodn_matrix_manpower add active int(1) default 0;
update m_prodn_matrix_manpower set active=1;
alter table m_prodn_fish_cutting add active int(1) default 0;
update m_prodn_fish_cutting set active=1;
alter table m_prodn_marketing add active int(1) default 0;
update m_prodn_marketing set active=1;
alter table m_packing_material_cost add active int(1) default 0;
update m_packing_material_cost set active=1;
alter table m_packing_sealing_cost add active int(1) default 0;
update m_packing_sealing_cost set active=1;
alter table ing_category add active int(1) default 0;
update ing_category set active=1;
alter table m_ingredient add active int(1) default 0;
update m_ingredient set active=1;
alter table ing_main_category add active int(1) default 0;
update ing_main_category set active=1;
alter table m_paymentterms add active int(1) default 0;
update m_paymentterms set active=1;
alter table m_common_reason add active int(1) default 0;
update m_common_reason set active=1;
alter table m_competitor add active int(1) default 0;
update m_competitor set active=1;
alter table m_packing_labour_cost add active int(1) default 0;
update m_packing_labour_cost set active=1;
alter table supplier add activeconfirm int(1) default 0;
update supplier set activeconfirm=1